update _samtools and fix a bug
kloetzl/biozsh pull request #12
Opened 2018-09-26 03:32 UTC by cgjosephlee

Update to samtools v1.8, but not all subcommands are implemented.

And v1.9 removes some options in mpileup, I haven't updated to this version yet.

2018-09-26 03:40 UTC, cgjosephlee commented
Just curious, how does this `if` clause work?
https://github.com/kloetzl/biozsh/blob/c163056182bd1fcceefae3516695abdaba37eac4/completions/_samtools#L271

I guess if the subcommand is not defined, it will show a warning message. I have tried a few circumstances and did not see the message popup.
Would you please give a brief explanation?

2018-09-26 09:13 UTC, kloetzl commented
> Would you please give a brief explanation?

Quoting from the [docs](http://zsh.sourceforge.net/Doc/Release/Completion-System.html):

> If a function name exists, it is called with the arguments args. The return argument gives the name of a parameter in which the return status from the function name should be stored; if return is empty or a single hyphen it is ignored.
>
> The return status of _call_function itself is zero if the function name exists and was called and non-zero otherwise.

If you do not see the message, maybe your zsh theme simply just doesn't show them? I had to add the following lines to my dotfiles to see them. [source](https://github.com/kloetzl/dotfiles/blob/master/zsh/completion.zsh#L90-L95).

```zsh
# Display message when no matches are found
# formatting and messages
zstyle ':completion:*' verbose yes
zstyle ':completion:*:descriptions' format '%B%d%b'
zstyle ':completion:*:messages' format '%d'
zstyle ':completion:*:warnings' format 'No matches for: %B%d%b'
```

2018-09-26 09:24 UTC, kloetzl requested changes

2018-09-26 09:24 UTC, kloetzl commented on completions/_samtools
> +			SAM\:SAM
When the description is the same as the key a simpler format can be used. `-O+[output format]:str:(SAM BAM CRAM)`. See [the docs](http://zsh.sourceforge.net/Doc/Release/Completion-System.html) under `_arguments`.

2018-09-26 09:24 UTC, kloetzl commented on completions/_samtools
> +		'-h[copy the header in FILE to <out.bam>]:FILE:_files'
Good catch.

2018-09-26 09:24 UTC, kloetzl commented on completions/_samtools
> +		'-o+[write final output to FILE]:files:_files'
If the output is in SAM, BAM, or CRAM format, maybe we can restrict suggestions to `*.sam` etc. here?

2018-09-26 10:07 UTC, cgjosephlee commented on completions/_samtools
> +			SAM\:SAM
Thank you. I will tidy this up.

2018-09-26 10:07 UTC, cgjosephlee commented on completions/_samtools
> +		'-o+[write final output to FILE]:files:_files'
Well, sometimes I use completion for naming prefix therefore I would not second this. But this is good for input suggestions.
e.g. auto-complete `abc123def456.fastq.gz` and thereafter edit as `abc123def456.sam`

2018-09-26 10:29 UTC, kloetzl commented on completions/_samtools
> +		'-o+[write final output to FILE]:files:_files'
You are right, output is different from input because the target file may not exist yet.

2018-09-26 13:24 UTC, cgjosephlee commented
update `samtools view` options.

2018-10-26 09:09 UTC, cgjosephlee commented
Commits rebased!

2018-11-01 10:08 UTC, kloetzl commented
Merged, thanks!

2018-11-01 10:08 UTC, closed without merging